from __future__ import annotations

import hashlib
import hmac
import json
import re
import secrets
import sqlite3
from collections import Counter
from datetime import datetime, timedelta, timezone
from typing import Any

from .config import DATABASE_URL, DB_BACKEND, DB_PATH, DATA_DIR, SESSION_HOURS
from .seed_data import (
    DEMO_ASSIGNMENTS,
    DEMO_ATTEMPTS,
    DEMO_ORGANIZATION,
    DEMO_STUDENT_GROUPS,
    DEMO_USERS,
    PRACTITIONER_PROGRAM,
    SEED_EXERCISES,
)

FREE_PUBLIC_MODEL_SLUGS = ("metamodel",)
FREE_PUBLIC_MODULE_TITLES = ("De kunst van magische taalpatronen",)

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None
    dict_row = None


IntegrityError = sqlite3.IntegrityError

POSTGRES_ID_TABLES = {
    "organizations",
    "themes",
    "users",
    "memberships",
    "programs",
    "modules",
    "topics",
    "concepts",
    "resources",
    "exercises",
    "assignments",
    "student_groups",
    "student_group_members",
    "assignment_items",
    "assignment_reference_modules",
    "assignment_targets",
    "assignment_target_groups",
    "attempts",
    "responses",
    "module_quiz_sessions",
    "reviews",
    "subscription_plans",
    "user_subscriptions",
    "plan_model_access",
    "plan_module_access",
}

POSTGRES_RESET_TABLES = [
    "plan_module_access",
    "plan_model_access",
    "user_subscriptions",
    "subscription_plans",
    "reviews",
    "module_quiz_sessions",
    "responses",
    "attempts",
    "assignment_target_groups",
    "assignment_targets",
    "assignment_reference_modules",
    "assignment_items",
    "student_group_members",
    "student_groups",
    "assignments",
    "exercises",
    "resources",
    "concepts",
    "topics",
    "modules",
    "programs",
    "memberships",
    "sessions",
    "themes",
    "organizations",
    "users",
]


class PostgresCursorWrapper:
    def __init__(self, cursor, *, buffered_rows: list[dict[str, Any]] | None = None, lastrowid: int | None = None) -> None:
        self._cursor = cursor
        self._buffered_rows = buffered_rows or []
        self.lastrowid = lastrowid

    def fetchone(self):
        if self._buffered_rows:
            return self._buffered_rows.pop(0)
        return self._cursor.fetchone()

    def fetchall(self):
        rows = list(self._buffered_rows)
        self._buffered_rows.clear()
        rows.extend(self._cursor.fetchall())
        return rows

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount


class PostgresConnectionWrapper:
    def __init__(self, connection) -> None:
        self._connection = connection

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if exc_type is None:
            self._connection.commit()
        else:
            self._connection.rollback()
        self._connection.close()

    def _translate_sql(self, sql: str) -> str:
        translated = sql
        ignore_insert = bool(re.match(r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b", translated, flags=re.IGNORECASE))
        if ignore_insert:
            translated = re.sub(
                r"^\s*INSERT\s+OR\s+IGNORE\s+INTO\b",
                "INSERT INTO",
                translated,
                count=1,
                flags=re.IGNORECASE,
            )
        translated = translated.replace("?", "%s")
        translated = translated.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )
        translated = translated.replace(" REAL ", " DOUBLE PRECISION ")
        translated = translated.replace("(REAL ", "(DOUBLE PRECISION ")
        translated = translated.replace(" REAL,", " DOUBLE PRECISION,")
        translated = translated.replace(" REAL\n", " DOUBLE PRECISION\n")
        if ignore_insert:
            translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
        return translated

    def _inject_returning_id(self, sql: str) -> tuple[str, str | None]:
        match = re.match(r"^\s*INSERT\s+INTO\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, flags=re.IGNORECASE)
        if not match or "RETURNING" in sql.upper():
            return sql, None
        table_name = match.group(1).lower()
        if table_name not in POSTGRES_ID_TABLES:
            return sql, None
        return sql.rstrip().rstrip(";") + " RETURNING id", table_name

    def execute(self, sql: str, params: tuple | list | None = None):
        translated = self._translate_sql(sql)
        translated, returning_table = self._inject_returning_id(translated)
        cursor = self._connection.cursor()
        try:
            cursor.execute(translated, tuple(params or ()))
        except Exception as exc:
            if psycopg is not None and isinstance(exc, psycopg.IntegrityError):
                raise sqlite3.IntegrityError(str(exc)) from exc
            raise
        if returning_table:
            row = cursor.fetchone()
            lastrowid = row["id"] if row else None
            buffered_rows = [row] if row else []
            return PostgresCursorWrapper(cursor, buffered_rows=buffered_rows, lastrowid=lastrowid)
        return PostgresCursorWrapper(cursor)

    def executescript(self, script: str) -> None:
        statements = [statement.strip() for statement in script.split(";") if statement.strip()]
        for statement in statements:
            self.execute(statement)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def utc_now_iso() -> str:
    return utc_now().isoformat(timespec="seconds")


def connect():
    if DB_BACKEND == "postgres":
        if psycopg is None:
            raise RuntimeError("DATABASE_URL is set, but psycopg is not installed.")
        raw_connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return PostgresConnectionWrapper(raw_connection)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def reset_postgres_database(connection) -> None:
    for table_name in POSTGRES_RESET_TABLES:
        connection.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE")


def initialize_database(reset: bool = False) -> None:
    if reset:
        if DB_BACKEND == "postgres":
            with connect() as connection:
                reset_postgres_database(connection)
                connection.commit()
        elif DB_PATH.exists():
            DB_PATH.unlink()

    with connect() as connection:
        create_schema(connection)
        seed_database(connection)
        apply_runtime_migrations(connection)


def validate_seed_exercises() -> None:
    title_counts = Counter(exercise["title"] for exercise in SEED_EXERCISES)
    duplicate_titles = sorted(title for title, count in title_counts.items() if count > 1)
    if duplicate_titles:
        preview = ", ".join(duplicate_titles[:5])
        suffix = " ..." if len(duplicate_titles) > 5 else ""
        raise ValueError(
            f"Duplicate exercise titles detected in seed data ({len(duplicate_titles)}): "
            f"{preview}{suffix}"
        )


def create_schema(connection) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS organizations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            slug TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS themes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NOT NULL UNIQUE,
            brand_name TEXT NOT NULL,
            logo_label TEXT NOT NULL,
            logo_url TEXT NOT NULL DEFAULT '',
            hero_url TEXT NOT NULL DEFAULT '',
            primary_color TEXT NOT NULL,
            secondary_color TEXT NOT NULL,
            accent_color TEXT NOT NULL,
            surface_color TEXT NOT NULL,
            background_style TEXT NOT NULL,
            background_image_opacity REAL NOT NULL DEFAULT 0.18,
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,
            is_platform_admin INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            account_kind TEXT NOT NULL DEFAULT 'managed',
            managed_by_user_id INTEGER NULL
        );

        CREATE TABLE IF NOT EXISTS memberships (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            organization_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE (user_id, organization_id, role),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS programs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NULL,
            title TEXT NOT NULL,
            level TEXT NOT NULL,
            description TEXT NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
        );

        CREATE TABLE IF NOT EXISTS modules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            program_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            summary TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS topics (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            module_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            summary TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS concepts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            topic_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            summary TEXT NOT NULL,
            tags_json TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS resources (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            module_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            resource_type TEXT NOT NULL,
            content TEXT NOT NULL,
            sort_order INTEGER NOT NULL,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS exercises (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NULL,
            module_id INTEGER NOT NULL,
            topic_id INTEGER NULL,
            concept_id INTEGER NULL,
            title TEXT NOT NULL UNIQUE,
            exercise_type TEXT NOT NULL,
            mode_support TEXT NOT NULL,
            difficulty TEXT NOT NULL,
            instructions TEXT NOT NULL,
            prompt TEXT NOT NULL,
            content_json TEXT NOT NULL,
            scoring_json TEXT NOT NULL,
            max_score REAL NOT NULL,
            requires_manual_review INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'published',
            created_at TEXT NOT NULL,
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE,
            FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE SET NULL,
            FOREIGN KEY (concept_id) REFERENCES concepts(id) ON DELETE SET NULL
        );

        CREATE TABLE IF NOT EXISTS assignments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NOT NULL,
            created_by_user_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            mode TEXT NOT NULL,
            due_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            created_at TEXT NOT NULL,
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
            FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS student_groups (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            organization_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            created_by_user_id INTEGER NULL,
            created_at TEXT NOT NULL,
            UNIQUE (organization_id, name),
            FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
            FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
        );

        CREATE TABLE IF NOT EXISTS student_group_members (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            group_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            UNIQUE (group_id, user_id),
            FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS assignment_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            assignment_id INTEGER NOT NULL,
            exercise_id INTEGER NOT NULL,
            sort_order INTEGER NOT NULL,
            UNIQUE (assignment_id, exercise_id),
            FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS assignment_reference_modules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            assignment_id INTEGER NOT NULL,
            module_id INTEGER NOT NULL,
            sort_order INTEGER NOT NULL,
            UNIQUE (assignment_id, module_id),
            FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS assignment_targets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            assignment_id INTEGER NOT NULL,
            target_user_id INTEGER NOT NULL,
            UNIQUE (assignment_id, target_user_id),
            FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS assignment_target_groups (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            assignment_id INTEGER NOT NULL,
            group_id INTEGER NOT NULL,
            UNIQUE (assignment_id, group_id),
            FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS attempts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            assignment_id INTEGER NULL,
            exercise_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            started_at TEXT NOT NULL,
            submitted_at TEXT NOT NULL,
            status TEXT NOT NULL,
            auto_score REAL NULL,
            manual_score REAL NULL,
            max_score REAL NOT NULL,
            feedback TEXT NOT NULL DEFAULT '',
            FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE,
            FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS responses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            attempt_id INTEGER NOT NULL UNIQUE,
            response_json TEXT NOT NULL,
            FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS module_quiz_sessions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            module_id INTEGER NOT NULL,
            queue_json TEXT NOT NULL,
            current_position INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'active',
            updated_at TEXT NOT NULL,
            UNIQUE (user_id, module_id),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS reviews (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            attempt_id INTEGER NOT NULL UNIQUE,
            reviewer_user_id INTEGER NOT NULL,
            score_override REAL NULL,
            feedback TEXT NOT NULL,
            reviewed_at TEXT NOT NULL,
            FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
            FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS subscription_plans (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            audience TEXT NOT NULL,
            access_scope TEXT NOT NULL,
            is_paid INTEGER NOT NULL DEFAULT 0,
            price_label TEXT NOT NULL DEFAULT '',
            description TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS user_subscriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            plan_id INTEGER NOT NULL,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            ends_at TEXT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS plan_model_access (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            plan_id INTEGER NOT NULL,
            model_slug TEXT NOT NULL,
            UNIQUE (plan_id, model_slug),
            FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS plan_module_access (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            plan_id INTEGER NOT NULL,
            module_id INTEGER NOT NULL,
            UNIQUE (plan_id, module_id),
            FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE,
            FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS sessions (
            token TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            csrf_token TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );
        """
    )
    ensure_column(connection, "themes", "background_image_opacity", "REAL NOT NULL DEFAULT 0.18")
    ensure_column(connection, "users", "account_kind", "TEXT NOT NULL DEFAULT 'managed'")
    ensure_column(connection, "users", "managed_by_user_id", "INTEGER NULL")


def ensure_column(connection, table: str, column: str, definition: str) -> None:
    if DB_BACKEND == "postgres":
        columns = {
            row["column_name"]
            for row in connection.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s
                """,
                (table,),
            ).fetchall()
        }
    else:
        columns = {row["name"] for row in connection.execute(f"PRAGMA table_info({table})").fetchall()}
    if column not in columns:
        connection.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def apply_runtime_migrations(connection) -> None:
    connection.execute(
        """
        UPDATE modules
        SET title = 'De geschiedenis van NLP'
        WHERE title = '0. In het begin'
        """
    )
    connection.execute(
        """
        UPDATE modules
        SET title = 'Fundamenten van NLP'
        WHERE title = '1. Fundamenten van NLP'
        """
    )
    connection.execute(
        """
        UPDATE themes
        SET background_image_opacity = COALESCE(background_image_opacity, 0.18)
        """
    )
    backfill_account_partitions(connection)
    sync_reference_curriculum(connection)
    sync_demo_student_groups(connection)
    sync_subscription_catalog(connection)
    backfill_public_subscriptions(connection)
    connection.commit()


def hash_password(password: str) -> str:
    salt = secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt.encode("utf-8"),
        120_000,
    )
    return f"{salt}${digest.hex()}"


def verify_password(password: str, password_hash: str) -> bool:
    salt, known_digest = password_hash.split("$", 1)
    computed = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt.encode("utf-8"),
        120_000,
    ).hex()
    return hmac.compare_digest(computed, known_digest)


def create_session(connection, user_id: int) -> tuple[str, str]:
    token = secrets.token_urlsafe(32)
    csrf_token = secrets.token_urlsafe(24)
    expires_at = (utc_now() + timedelta(hours=SESSION_HOURS)).isoformat(timespec="seconds")
    connection.execute(
        "INSERT INTO sessions (token, user_id, csrf_token, expires_at) VALUES (?, ?, ?, ?)",
        (token, user_id, csrf_token, expires_at),
    )
    connection.commit()
    return token, csrf_token


def get_session(connection, token: str | None):
    if not token:
        return None

    session = connection.execute(
        """
        SELECT sessions.token, sessions.user_id, sessions.csrf_token, sessions.expires_at,
               users.email, users.first_name, users.last_name, users.is_platform_admin,
               users.account_kind, users.managed_by_user_id
        FROM sessions
        JOIN users ON users.id = sessions.user_id
        WHERE sessions.token = ?
        """,
        (token,),
    ).fetchone()
    if not session:
        return None

    if datetime.fromisoformat(session["expires_at"]) <= utc_now():
        destroy_session(connection, token)
        return None

    return session


def destroy_session(connection, token: str | None) -> None:
    if not token:
        return
    connection.execute("DELETE FROM sessions WHERE token = ?", (token,))
    connection.commit()


def get_memberships(connection, user_id: int):
    return connection.execute(
        """
        SELECT memberships.*, organizations.name AS organization_name, organizations.slug AS organization_slug
        FROM memberships
        JOIN organizations ON organizations.id = memberships.organization_id
        WHERE memberships.user_id = ?
        ORDER BY organizations.name, memberships.role
        """,
        (user_id,),
    ).fetchall()


def create_user_account(
    connection,
    *,
    email: str,
    password: str,
    first_name: str,
    last_name: str,
    account_kind: str,
    managed_by_user_id: int | None = None,
    is_platform_admin: bool = False,
) -> int:
    if account_kind not in {"managed", "public"}:
        raise ValueError("account_kind must be 'managed' or 'public'.")
    cursor = connection.execute(
        """
        INSERT INTO users (
            email, password_hash, first_name, last_name, is_platform_admin, created_at, account_kind, managed_by_user_id
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            email.strip().lower(),
            hash_password(password),
            first_name.strip(),
            last_name.strip(),
            1 if is_platform_admin else 0,
            utc_now_iso(),
            account_kind,
            managed_by_user_id,
        ),
    )
    return cursor.lastrowid


def get_plan_by_code(connection, code: str):
    return connection.execute(
        "SELECT * FROM subscription_plans WHERE code = ?",
        (code,),
    ).fetchone()


def get_active_subscription(connection, user_id: int):
    return connection.execute(
        """
        SELECT user_subscriptions.*, subscription_plans.code AS plan_code, subscription_plans.name AS plan_name,
               subscription_plans.audience, subscription_plans.access_scope, subscription_plans.is_paid,
               subscription_plans.price_label, subscription_plans.description
        FROM user_subscriptions
        JOIN subscription_plans ON subscription_plans.id = user_subscriptions.plan_id
        WHERE user_subscriptions.user_id = ?
          AND user_subscriptions.status = 'active'
        ORDER BY user_subscriptions.started_at DESC, user_subscriptions.id DESC
        LIMIT 1
        """,
        (user_id,),
    ).fetchone()


def set_active_subscription(connection, user_id: int, plan_code: str):
    plan = get_plan_by_code(connection, plan_code)
    if not plan:
        raise ValueError(f"Unknown subscription plan: {plan_code}")

    current_active = connection.execute(
        "SELECT id FROM user_subscriptions WHERE user_id = ? AND status = 'active'",
        (user_id,),
    ).fetchall()
    for row in current_active:
        connection.execute(
            """
            UPDATE user_subscriptions
            SET status = 'replaced', ends_at = ?
            WHERE id = ?
            """,
            (utc_now_iso(), row["id"]),
        )

    connection.execute(
        """
        INSERT INTO user_subscriptions (user_id, plan_id, status, started_at, ends_at, created_at)
        VALUES (?, ?, 'active', ?, NULL, ?)
        """,
        (user_id, plan["id"], utc_now_iso(), utc_now_iso()),
    )
    return get_active_subscription(connection, user_id)


def ensure_public_free_subscription(connection, user_id: int):
    active_subscription = get_active_subscription(connection, user_id)
    if active_subscription:
        return active_subscription
    return set_active_subscription(connection, user_id, "public_free")


def activate_public_paid_subscription(connection, user_id: int):
    return set_active_subscription(connection, user_id, "public_paid")


def get_plan_model_access_slugs(connection, plan_id: int) -> set[str]:
    return {
        row["model_slug"]
        for row in connection.execute(
            "SELECT model_slug FROM plan_model_access WHERE plan_id = ?",
            (plan_id,),
        ).fetchall()
    }


def get_plan_module_access_ids(connection, plan_id: int) -> set[int]:
    return {
        int(row["module_id"])
        for row in connection.execute(
            "SELECT module_id FROM plan_module_access WHERE plan_id = ?",
            (plan_id,),
        ).fetchall()
    }


def export_account_access_rows(connection, organization_id: int | None = None):
    where_clause = ""
    parameters: tuple = ()
    if organization_id is not None:
        where_clause = "WHERE memberships.organization_id = ?"
        parameters = (organization_id,)
    return connection.execute(
        f"""
        SELECT users.id AS user_id,
               users.email,
               users.first_name,
               users.last_name,
               users.account_kind,
               manager.email AS managed_by_email,
               users.created_at,
               COALESCE(
                   GROUP_CONCAT(DISTINCT organizations.name || ' [' || memberships.role || ']'),
                   ''
               ) AS organization_access,
               COALESCE(subscription_plans.code, '') AS subscription_plan,
               COALESCE(user_subscriptions.status, '') AS subscription_status,
               COALESCE(user_subscriptions.started_at, '') AS subscription_started_at,
               COALESCE(subscription_plans.access_scope, '') AS access_scope
        FROM users
        LEFT JOIN users AS manager ON manager.id = users.managed_by_user_id
        LEFT JOIN memberships ON memberships.user_id = users.id
        LEFT JOIN organizations ON organizations.id = memberships.organization_id
        LEFT JOIN user_subscriptions
               ON user_subscriptions.user_id = users.id
              AND user_subscriptions.status = 'active'
        LEFT JOIN subscription_plans ON subscription_plans.id = user_subscriptions.plan_id
        {where_clause}
        GROUP BY users.id, manager.email, user_subscriptions.id, subscription_plans.id
        ORDER BY users.created_at DESC, users.email
        """,
        parameters,
    ).fetchall()


def effective_score(attempt) -> float | None:
    if attempt["manual_score"] is not None:
        return float(attempt["manual_score"])
    if attempt["auto_score"] is not None:
        return float(attempt["auto_score"])
    return None


def sync_reference_curriculum(connection) -> None:
    created_at = utc_now_iso()
    program_row = connection.execute(
        "SELECT id FROM programs WHERE title = ?",
        (PRACTITIONER_PROGRAM["title"],),
    ).fetchone()
    if program_row:
        program_id = program_row["id"]
        connection.execute(
            """
            UPDATE programs
            SET level = ?, description = ?
            WHERE id = ?
            """,
            (
                PRACTITIONER_PROGRAM["level"],
                PRACTITIONER_PROGRAM["description"],
                program_id,
            ),
        )
    else:
        cursor = connection.execute(
            """
            INSERT INTO programs (organization_id, title, level, description, created_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                None,
                PRACTITIONER_PROGRAM["title"],
                PRACTITIONER_PROGRAM["level"],
                PRACTITIONER_PROGRAM["description"],
                created_at,
            ),
        )
        program_id = cursor.lastrowid

    module_ids: dict[str, int] = {}
    topic_ids: dict[tuple[str, str], int] = {}
    concept_ids: dict[tuple[str, str, str], int] = {}

    for module_index, module in enumerate(PRACTITIONER_PROGRAM["modules"], start=1):
        existing_module = connection.execute(
            "SELECT id FROM modules WHERE program_id = ? AND title = ?",
            (program_id, module["title"]),
        ).fetchone()
        if existing_module:
            module_id = existing_module["id"]
            connection.execute(
                "UPDATE modules SET summary = ?, sort_order = ? WHERE id = ?",
                (module["summary"], module_index, module_id),
            )
        else:
            cursor = connection.execute(
                "INSERT INTO modules (program_id, title, summary, sort_order) VALUES (?, ?, ?, ?)",
                (program_id, module["title"], module["summary"], module_index),
            )
            module_id = cursor.lastrowid
        module_ids[module["title"]] = module_id

        connection.execute("DELETE FROM resources WHERE module_id = ?", (module_id,))
        connection.execute("DELETE FROM topics WHERE module_id = ?", (module_id,))

        for resource in module.get("resources", []):
            connection.execute(
                """
                INSERT INTO resources (module_id, title, resource_type, content, sort_order)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    module_id,
                    resource["title"],
                    resource["resource_type"],
                    resource["content"],
                    resource["sort_order"],
                ),
            )

        for topic_index, topic in enumerate(module["topics"], start=1):
            cursor = connection.execute(
                "INSERT INTO topics (module_id, title, summary, sort_order) VALUES (?, ?, ?, ?)",
                (module_id, topic["title"], topic["summary"], topic_index),
            )
            topic_id = cursor.lastrowid
            topic_ids[(module["title"], topic["title"])] = topic_id

            for concept_index, concept in enumerate(topic["concepts"], start=1):
                cursor = connection.execute(
                    """
                    INSERT INTO concepts (topic_id, title, summary, tags_json, sort_order)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        topic_id,
                        concept["title"],
                        concept["summary"],
                        json.dumps(concept["tags"]),
                        concept_index,
                    ),
                )
                concept_ids[(module["title"], topic["title"], concept["title"])] = cursor.lastrowid

    for exercise in SEED_EXERCISES:
        module_id = module_ids[exercise["module_title"]]
        topic_id = topic_ids.get((exercise["module_title"], exercise["topic_title"]))
        concept_id = concept_ids.get(
            (exercise["module_title"], exercise["topic_title"], exercise["concept_title"])
        )
        payload = (
            None,
            module_id,
            topic_id,
            concept_id,
            exercise["exercise_type"],
            exercise["mode_support"],
            exercise["difficulty"],
            exercise["instructions"],
            exercise["prompt"],
            json.dumps(exercise["content"]),
            json.dumps(exercise["scoring"]),
            float(exercise["max_score"]),
            1 if exercise["requires_manual_review"] else 0,
            created_at,
            exercise["title"],
        )
        existing_exercise = connection.execute(
            "SELECT id FROM exercises WHERE title = ?",
            (exercise["title"],),
        ).fetchone()
        if existing_exercise:
            connection.execute(
                """
                UPDATE exercises
                SET organization_id = ?, module_id = ?, topic_id = ?, concept_id = ?,
                    exercise_type = ?, mode_support = ?, difficulty = ?, instructions = ?,
                    prompt = ?, content_json = ?, scoring_json = ?, max_score = ?,
                    requires_manual_review = ?, status = 'published', created_at = ?
                WHERE title = ?
                """,
                payload,
            )
        else:
            connection.execute(
                """
                INSERT INTO exercises (
                    organization_id, module_id, topic_id, concept_id, title, exercise_type,
                    mode_support, difficulty, instructions, prompt, content_json, scoring_json,
                    max_score, requires_manual_review, status, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'published', ?)
                """,
                (
                    None,
                    module_id,
                    topic_id,
                    concept_id,
                    exercise["title"],
                    exercise["exercise_type"],
                    exercise["mode_support"],
                    exercise["difficulty"],
                    exercise["instructions"],
                    exercise["prompt"],
                    json.dumps(exercise["content"]),
                    json.dumps(exercise["scoring"]),
                    float(exercise["max_score"]),
                    1 if exercise["requires_manual_review"] else 0,
                    created_at,
                ),
            )

    if SEED_EXERCISES:
        seed_titles = [exercise["title"] for exercise in SEED_EXERCISES]
        placeholders = ", ".join("?" for _ in seed_titles)
        connection.execute(
            f"""
            UPDATE exercises
            SET status = 'archived'
            WHERE organization_id IS NULL
              AND title NOT IN ({placeholders})
            """,
            tuple(seed_titles),
        )


def seed_database(connection) -> None:
    existing_users = connection.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
    if existing_users:
        return

    from .scoring import score_submission

    validate_seed_exercises()
    created_at = utc_now_iso()

    connection.execute(
        "INSERT INTO organizations (name, slug, description, created_at) VALUES (?, ?, ?, ?)",
        (
            DEMO_ORGANIZATION["name"],
            DEMO_ORGANIZATION["slug"],
            DEMO_ORGANIZATION["description"],
            created_at,
        ),
    )
    organization_id = connection.execute(
        "SELECT id FROM organizations WHERE slug = ?",
        (DEMO_ORGANIZATION["slug"],),
    ).fetchone()["id"]

    theme = DEMO_ORGANIZATION["theme"]
    connection.execute(
        """
        INSERT INTO themes (
            organization_id, brand_name, logo_label, logo_url, hero_url,
            primary_color, secondary_color, accent_color, surface_color, background_style,
            background_image_opacity
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            organization_id,
            theme["brand_name"],
            theme["logo_label"],
            theme["logo_url"],
            theme["hero_url"],
            theme["primary_color"],
            theme["secondary_color"],
            theme["accent_color"],
            theme["surface_color"],
            theme["background_style"],
            theme.get("background_image_opacity", 0.18),
        ),
    )

    user_ids: dict[str, int] = {}
    for user in DEMO_USERS:
        cursor = connection.execute(
            """
            INSERT INTO users (
                email, password_hash, first_name, last_name, is_platform_admin, created_at, account_kind, managed_by_user_id
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                user["email"],
                hash_password(user["password"]),
                user["first_name"],
                user["last_name"],
                1 if user["is_platform_admin"] else 0,
                created_at,
                user.get("account_kind", "managed"),
                user_ids.get(user.get("managed_by_email")),
            ),
        )
        user_ids[user["email"]] = cursor.lastrowid
        for role in user["memberships"]:
            connection.execute(
                "INSERT INTO memberships (user_id, organization_id, role, created_at) VALUES (?, ?, ?, ?)",
                (user_ids[user["email"]], organization_id, role, created_at),
            )

    for group in DEMO_STUDENT_GROUPS:
        cursor = connection.execute(
            """
            INSERT INTO student_groups (organization_id, name, created_by_user_id, created_at)
            VALUES (?, ?, ?, ?)
            """,
            (
                organization_id,
                group["name"],
                user_ids.get("admin@neuroflow.local"),
                created_at,
            ),
        )
        group_id = cursor.lastrowid
        for student_email in group["student_emails"]:
            connection.execute(
                "INSERT INTO student_group_members (group_id, user_id) VALUES (?, ?)",
                (group_id, user_ids[student_email]),
            )

    cursor = connection.execute(
        """
        INSERT INTO programs (organization_id, title, level, description, created_at)
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            None,
            PRACTITIONER_PROGRAM["title"],
            PRACTITIONER_PROGRAM["level"],
            PRACTITIONER_PROGRAM["description"],
            created_at,
        ),
    )
    program_id = cursor.lastrowid

    module_ids: dict[str, int] = {}
    topic_ids: dict[tuple[str, str], int] = {}
    concept_ids: dict[tuple[str, str, str], int] = {}

    for module_index, module in enumerate(PRACTITIONER_PROGRAM["modules"], start=1):
        cursor = connection.execute(
            "INSERT INTO modules (program_id, title, summary, sort_order) VALUES (?, ?, ?, ?)",
            (program_id, module["title"], module["summary"], module_index),
        )
        module_id = cursor.lastrowid
        module_ids[module["title"]] = module_id

        for resource in module.get("resources", []):
            connection.execute(
                """
                INSERT INTO resources (module_id, title, resource_type, content, sort_order)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    module_id,
                    resource["title"],
                    resource["resource_type"],
                    resource["content"],
                    resource["sort_order"],
                ),
            )

        for topic_index, topic in enumerate(module["topics"], start=1):
            cursor = connection.execute(
                "INSERT INTO topics (module_id, title, summary, sort_order) VALUES (?, ?, ?, ?)",
                (module_id, topic["title"], topic["summary"], topic_index),
            )
            topic_id = cursor.lastrowid
            topic_ids[(module["title"], topic["title"])] = topic_id

            for concept_index, concept in enumerate(topic["concepts"], start=1):
                cursor = connection.execute(
                    """
                    INSERT INTO concepts (topic_id, title, summary, tags_json, sort_order)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        topic_id,
                        concept["title"],
                        concept["summary"],
                        json.dumps(concept["tags"]),
                        concept_index,
                    ),
                )
                concept_ids[(module["title"], topic["title"], concept["title"])] = cursor.lastrowid

    exercise_ids: dict[str, int] = {}
    for exercise in SEED_EXERCISES:
        module_id = module_ids[exercise["module_title"]]
        topic_id = topic_ids.get((exercise["module_title"], exercise["topic_title"]))
        concept_id = concept_ids.get(
            (exercise["module_title"], exercise["topic_title"], exercise["concept_title"])
        )
        cursor = connection.execute(
            """
            INSERT INTO exercises (
                organization_id, module_id, topic_id, concept_id, title, exercise_type,
                mode_support, difficulty, instructions, prompt, content_json, scoring_json,
                max_score, requires_manual_review, status, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'published', ?)
            """,
            (
                None,
                module_id,
                topic_id,
                concept_id,
                exercise["title"],
                exercise["exercise_type"],
                exercise["mode_support"],
                exercise["difficulty"],
                exercise["instructions"],
                exercise["prompt"],
                json.dumps(exercise["content"]),
                json.dumps(exercise["scoring"]),
                float(exercise["max_score"]),
                1 if exercise["requires_manual_review"] else 0,
                created_at,
            ),
        )
        exercise_ids[exercise["title"]] = cursor.lastrowid

    assignment_ids: dict[str, int] = {}
    for assignment in DEMO_ASSIGNMENTS:
        due_date = (utc_now() + timedelta(days=assignment["due_in_days"])).date().isoformat()
        cursor = connection.execute(
            """
            INSERT INTO assignments (
                organization_id, created_by_user_id, title, description, mode, due_date, status, created_at
            ) VALUES (?, ?, ?, ?, ?, ?, 'active', ?)
            """,
            (
                organization_id,
                user_ids[assignment["created_by_email"]],
                assignment["title"],
                assignment["description"],
                assignment["mode"],
                due_date,
                created_at,
            ),
        )
        assignment_id = cursor.lastrowid
        assignment_ids[assignment["title"]] = assignment_id

        for item_index, exercise_title in enumerate(assignment["exercise_titles"], start=1):
            connection.execute(
                "INSERT INTO assignment_items (assignment_id, exercise_id, sort_order) VALUES (?, ?, ?)",
                (assignment_id, exercise_ids[exercise_title], item_index),
            )

        for target_email in assignment["target_emails"]:
            connection.execute(
                "INSERT INTO assignment_targets (assignment_id, target_user_id) VALUES (?, ?)",
                (assignment_id, user_ids[target_email]),
            )

    exercise_lookup = {row["title"]: dict(row) for row in connection.execute("SELECT * FROM exercises").fetchall()}

    for demo_attempt in DEMO_ATTEMPTS:
        assignment_row = connection.execute(
            "SELECT * FROM assignments WHERE title = ?",
            (demo_attempt["assignment_title"],),
        ).fetchone()
        exercise_row = exercise_lookup[demo_attempt["exercise_title"]]
        result = score_submission(
            exercise=exercise_row,
            response=demo_attempt["response"],
            mode=assignment_row["mode"],
        )
        cursor = connection.execute(
            """
            INSERT INTO attempts (
                assignment_id, exercise_id, user_id, started_at, submitted_at, status,
                auto_score, manual_score, max_score, feedback
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                assignment_row["id"],
                exercise_row["id"],
                user_ids[demo_attempt["student_email"]],
                created_at,
                created_at,
                "submitted" if result["requires_review"] else "scored",
                result["auto_score"],
                None,
                result["max_score"],
                result["feedback"],
            ),
        )
        attempt_id = cursor.lastrowid
        connection.execute(
            "INSERT INTO responses (attempt_id, response_json) VALUES (?, ?)",
            (attempt_id, json.dumps(demo_attempt["response"])),
        )

    connection.commit()


def sync_demo_student_groups(connection) -> None:
    organization_row = connection.execute(
        "SELECT id FROM organizations WHERE slug = ?",
        (DEMO_ORGANIZATION["slug"],),
    ).fetchone()
    if not organization_row:
        return

    organization_id = organization_row["id"]
    admin_row = connection.execute(
        "SELECT id FROM users WHERE email = ?",
        ("admin@neuroflow.local",),
    ).fetchone()
    admin_id = admin_row["id"] if admin_row else None

    for group in DEMO_STUDENT_GROUPS:
        existing_group = connection.execute(
            "SELECT id FROM student_groups WHERE organization_id = ? AND name = ?",
            (organization_id, group["name"]),
        ).fetchone()
        if existing_group:
            group_id = existing_group["id"]
        else:
            cursor = connection.execute(
                """
                INSERT INTO student_groups (organization_id, name, created_by_user_id, created_at)
                VALUES (?, ?, ?, ?)
                """,
                (organization_id, group["name"], admin_id, utc_now_iso()),
            )
            group_id = cursor.lastrowid
        if existing_group and admin_id is not None:
            connection.execute(
                "UPDATE student_groups SET created_by_user_id = ? WHERE id = ?",
                (admin_id, group_id),
            )

        connection.execute("DELETE FROM student_group_members WHERE group_id = ?", (group_id,))
        for student_email in group["student_emails"]:
            user_row = connection.execute(
                "SELECT id FROM users WHERE email = ?",
                (student_email,),
            ).fetchone()
            if user_row:
                connection.execute(
                    "INSERT OR IGNORE INTO student_group_members (group_id, user_id) VALUES (?, ?)",
                    (group_id, user_row["id"]),
                )


def backfill_account_partitions(connection) -> None:
    connection.execute(
        """
        UPDATE users
        SET account_kind = 'managed'
        WHERE id IN (SELECT DISTINCT user_id FROM memberships)
        """
    )
    connection.execute(
        """
        UPDATE users
        SET account_kind = 'public',
            managed_by_user_id = NULL
        WHERE is_platform_admin = 0
          AND id NOT IN (SELECT DISTINCT user_id FROM memberships)
        """
    )

    admin_row = connection.execute(
        "SELECT id FROM users WHERE email = ?",
        ("admin@neuroflow.local",),
    ).fetchone()
    if not admin_row:
        return

    admin_id = admin_row["id"]
    connection.execute(
        """
        UPDATE users
        SET account_kind = 'managed',
            managed_by_user_id = ?
        WHERE email IN ('student@neuroflow.local', 'student2@neuroflow.local')
        """,
        (admin_id,),
    )


def sync_subscription_catalog(connection) -> None:
    created_at = utc_now_iso()
    plans = [
        {
            "code": "public_free",
            "name": "Particulier gratis",
            "audience": "public",
            "access_scope": "public_limited",
            "is_paid": 0,
            "price_label": "Gratis",
            "description": "Kennismaking met 1 model en 1 leerpad.",
        },
        {
            "code": "public_paid",
            "name": "Particulier volledig",
            "audience": "public",
            "access_scope": "public_full",
            "is_paid": 1,
            "price_label": "Betaald",
            "description": "Volledige toegang tot alle publieke modellen en verdiepingspaden.",
        },
        {
            "code": "organization_full",
            "name": "Organisatie volledig",
            "audience": "organization",
            "access_scope": "organization_full",
            "is_paid": 1,
            "price_label": "Inbegrepen via organisatie",
            "description": "Volledige toegang via een betalende organisatie.",
        },
    ]

    for plan in plans:
        existing = get_plan_by_code(connection, plan["code"])
        if existing:
            connection.execute(
                """
                UPDATE subscription_plans
                SET name = ?, audience = ?, access_scope = ?, is_paid = ?, price_label = ?, description = ?
                WHERE code = ?
                """,
                (
                    plan["name"],
                    plan["audience"],
                    plan["access_scope"],
                    plan["is_paid"],
                    plan["price_label"],
                    plan["description"],
                    plan["code"],
                ),
            )
        else:
            connection.execute(
                """
                INSERT INTO subscription_plans (
                    code, name, audience, access_scope, is_paid, price_label, description, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    plan["code"],
                    plan["name"],
                    plan["audience"],
                    plan["access_scope"],
                    plan["is_paid"],
                    plan["price_label"],
                    plan["description"],
                    created_at,
                ),
            )

    free_plan = get_plan_by_code(connection, "public_free")
    if not free_plan:
        return

    connection.execute("DELETE FROM plan_model_access WHERE plan_id = ?", (free_plan["id"],))
    for model_slug in FREE_PUBLIC_MODEL_SLUGS:
        connection.execute(
            "INSERT OR IGNORE INTO plan_model_access (plan_id, model_slug) VALUES (?, ?)",
            (free_plan["id"], model_slug),
        )

    connection.execute("DELETE FROM plan_module_access WHERE plan_id = ?", (free_plan["id"],))
    for module_title in FREE_PUBLIC_MODULE_TITLES:
        module_row = connection.execute(
            "SELECT id FROM modules WHERE title = ?",
            (module_title,),
        ).fetchone()
        if module_row:
            connection.execute(
                "INSERT OR IGNORE INTO plan_module_access (plan_id, module_id) VALUES (?, ?)",
                (free_plan["id"], module_row["id"]),
            )


def backfill_public_subscriptions(connection) -> None:
    free_plan = get_plan_by_code(connection, "public_free")
    if not free_plan:
        return

    public_users = connection.execute(
        """
        SELECT users.id
        FROM users
        WHERE users.account_kind = 'public'
          AND NOT EXISTS (
              SELECT 1
              FROM user_subscriptions
              WHERE user_subscriptions.user_id = users.id
                AND user_subscriptions.status = 'active'
          )
        """
    ).fetchall()
    for row in public_users:
        connection.execute(
            """
            INSERT INTO user_subscriptions (user_id, plan_id, status, started_at, ends_at, created_at)
            VALUES (?, ?, 'active', ?, NULL, ?)
            """,
            (row["id"], free_plan["id"], utc_now_iso(), utc_now_iso()),
        )
